package io.github.cyfko.filterql.spring.autoconfigure;

import io.github.cyfko.filterql.jpa.JpaFilterContext;
import io.github.cyfko.filterql.spring.projection.ProjectionJacksonModule;
import io.github.cyfko.filterql.spring.support.FilterContextRegistry;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import java.util.List;

/**
 * Spring Boot {@link org.springframework.boot.autoconfigure.AutoConfiguration
 * AutoConfiguration}
 * that bootstraps the FilterQL runtime infrastructure.
 * <p>
 * This configuration is activated automatically when {@link JpaFilterContext}
 * is on the
 * classpath, and registers the following beans (unless already present):
 * </p>
 * <ul>
 * <li>{@link FilterContextRegistry} — aggregates all {@link JpaFilterContext}
 * beans
 * (typically generated by the annotation processor) into a single lookup
 * registry.</li>
 * <li>{@link ProjectionJacksonModule} — a Jackson
 * {@link com.fasterxml.jackson.databind.Module}
 * that enables correct JSON serialization of projection proxy objects, emitting
 * only the
 * projected fields and distinguishing {@code null} values from non-projected
 * fields.</li>
 * </ul>
 *
 * <p>
 * <strong>Overriding:</strong> Each bean is guarded by
 * {@code @ConditionalOnMissingBean},
 * so you can replace any of them by declaring your own bean of the same type.
 * </p>
 *
 * <p>
 * <strong>Edge case — missing Jackson module:</strong> If
 * {@code jackson-databind} is not
 * on the classpath, the {@code ProjectionJacksonModule} bean will not be
 * created. In that case,
 * serializing a
 * {@link io.github.cyfko.filterql.spring.projection.ProjectionProxy
 * ProjectionProxy}
 * with Jackson will fail because the default Jackson introspection will attempt
 * to call all
 * interface getters, including those for non-projected fields, triggering a
 * {@link io.github.cyfko.filterql.spring.projection.FieldNotProjectedException}.
 * </p>
 *
 * @see FilterContextRegistry
 * @see ProjectionJacksonModule
 * @see FilterQlProperties
 * @author Frank KOSSI
 * @since 4.0.0
 */
@AutoConfiguration
@ComponentScan(basePackages = "io.github.cyfko.filterql.spring")
@ConditionalOnClass(JpaFilterContext.class)
@EnableConfigurationProperties(FilterQlProperties.class)
public class FilterQlAutoConfiguration {

    @Bean
    @ConditionalOnMissingBean
    public FilterContextRegistry filterContextRegistry(List<JpaFilterContext<?>> contexts) {
        return new FilterContextRegistry(contexts);
    }

    @Bean
    @ConditionalOnMissingBean(ProjectionJacksonModule.class)
    public com.fasterxml.jackson.databind.Module filterQlProjectionJacksonModule() {
        return new ProjectionJacksonModule();
    }

}
