package io.github.cyfko.filterql.spring;

import io.github.cyfko.projection.MethodReference;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * REST API exposure options used in conjunction with {@link io.github.cyfko.projection.Projected} annotation.
 * When applied, this annotation implies generation of a search endpoint at {@code [base-path]/search/[resource-name-or-auto-generated-name]}
 * <p>
 * Allows configuring REST endpoint exposure, pagination settings, and documentation details.
 * </p>
 * <p>This annotation cannot be used standalone and serves only as an attribute within other annotations.</p>
 *
 * <h2>Configuration Options</h2>
 * <ul>
 *   <li><b>value</b>: name of the exposed REST resource in kebab-case. Defaults to kebab-case of the entity class name.</li>
 *   <li><b>endpoints</b>: determines if additional REST endpoints for this entity should be exposed. no other endpoints
 *   are generated by defaults to {@code true}.</li>
 *   <li><b>basePath</b>: optional URI path prefix for REST endpoints; kebab-case recommended.</li>
 * </ul>
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface Exposure {

    /**
     * Name of the REST resource exposed (kebab-case).
     * Defaults to the kebab-case form of the entity class name.
     */
    String value() default "";

    /**
     * Optional URI path prefix for the REST endpoints.
     * Kebab-case is recommended.
     */
    String basePath() default "";

    /**
     * Reference to a method containing annotation templates for generated endpoints.
     *
     * <h2>Convention over Configuration</h2>
     *
     * <h3>Default Behavior (no configuration needed)</h3>
     * If not specified, the processor automatically looks for a private static method named
     * {@code exposureEndpoint()} in the annotated class:
     * <pre>{@code
     * @Projection(from = User.class)
     * @Exposure(value = "users")
     * public class UserDTO {
     *
     *   @PreAuthorize("hasRole('ADMIN')")
     *   @Cacheable("userCache")
     *   private static void exposureEndpoint() {}
     * }
     * }</pre>
     *
     * <h3>Custom Method Name</h3>
     * Override the method name if you need multiple configurations or prefer a different name:
     * <pre>{@code
     * @Projection(from = User.class)
     * @Exposure(
     *   value = "users",
     *   annotationsFrom = @MethodReference(method = "adminSearchConfig")
     * )
     * public class UserDTO {
     *
     *   @PreAuthorize("hasRole('ADMIN')")
     *   @Cacheable("adminCache")
     *   private static void adminSearchConfig() {}
     * }
     * }</pre>
     *
     * <h3>External Template Class</h3>
     * Reference a shared template class for reusable configurations:
     * <pre>{@code
     * // Shared templates
     * public class SecurityTemplates {
     *   @PreAuthorize("hasRole('ADMIN')")
     *   @Cacheable("adminCache")
     *   @RateLimiter(name = "admin")
     *   public static void adminEndpoint() {}
     *
     *   @PreAuthorize("hasRole('USER')")
     *   @RateLimiter(name = "user")
     *   public static void userEndpoint() {}
     * }
     *
     * // Use in DTO
     * @Projection(from = User.class)
     * @Exposure(
     *   value = "users",
     *   annotationsFrom = @MethodReference(
     *     type = SecurityTemplates.class,
     *     method = "adminEndpoint"
     *   )
     * )
     * public class UserDTO { }
     * }</pre>
     *
     * <h3>Method Requirements</h3>
     * <ul>
     *   <li>Must be static</li>
     *   <li>Must return void</li>
     *   <li>Must take no parameters</li>
     *   <li>Should be private</li>
     *   <li>Method body is never executed - only annotations are extracted</li>
     * </ul>
     *
     * <h3>Resolution Order</h3>
     * <ol>
     *   <li>If {@code type} is specified → search in that class for the method</li>
     *   <li>If only {@code method} is specified → search in the annotated class</li>
     *   <li>If nothing is specified → search for {@code exposureEndpoint()} in the annotated class</li>
     * </ol>
     *
     * @return method reference for annotation extraction
     */
    MethodReference annotationsFrom() default @MethodReference();

}